/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import type { WorkboxPlugin } from 'workbox-core/types';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { REGION_API_PATH } from './shared/config/region';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
//
// The same-origin check is not incidental: OSM tiles are .png too, and caching
// them here would turn the app into the offline map the tile usage policy
// forbids. Do not widen this route to other origins.
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Responses from the beaches backend (different origin: Render).
//
// NetworkFirst with a short timeout: fresh data is attempted, but if the backend
// is asleep —Render free puts the process to sleep after 15 min and takes tens of
// seconds to wake up— the last cached response is served instead of leaving
// the user staring at a spinner. Intended side effect: the app remains
// useful at the beach with poor coverage, and revisits don't spend quota of the
// free APIs.
/** Posted to the open tabs together with the response that supersedes a cached one. */
const MENSAJE_API_ACTUALIZADA = 'API_ACTUALIZADA';

/**
 * Hands the tabs the answer that arrived late, instead of leaving them on the
 * stale one.
 *
 * `NetworkFirst` gives up on the network after three seconds and resolves the
 * request with the stored body, and at the `fetch` layer that is an ordinary
 * 200: the app could not tell last night's payload from this morning's. On
 * 2-sep-2026 the first load of the day painted night icons and yesterday's
 * temperatures, because the first `/featured` after the night is always a cold
 * recompute on the backend and always blows past the timeout. The request the
 * strategy abandoned does finish, and this is what makes its result arrive.
 *
 * The message CARRIES THE BODY, and that is the whole point: a message that
 * only said "there is something newer" would have the app fetch again, that
 * fetch would write the cache, writing the cache would fire this callback
 * again, and round it goes. Measured before fixing it: 634 messages in one
 * session against a backend on a free plan. Handing over the data closes the
 * loop — the app has nothing left to ask for.
 *
 * Marking the cached response with a header was tried first and cannot work:
 * the API is on another origin, so the browser CORS-filters the response the
 * worker returns and any header of ours is stripped before the page sees it.
 */
const entregarRespuestaNueva: WorkboxPlugin = {
  cacheDidUpdate: async ({ cacheName, oldResponse, request }) => {
    // Sin `oldResponse` esta entrada se llena por primera vez y la app ya está
    // pintando ese mismo cuerpo: no hay nada que corregir.
    if (!oldResponse) return;

    let datos: unknown;
    try {
      // Se relee del caché en vez de clonar `newResponse`: para cuando este
      // callback corre, workbox ya ha gastado ese cuerpo en el `cache.put`, y
      // clonarlo lanza. El fallo era mudo —el `catch` se lo tragaba— y el aviso
      // sencillamente no salía nunca.
      const cache = await caches.open(cacheName);
      const guardada = await cache.match(request);
      if (!guardada) return;
      datos = await guardada.json();
    } catch {
      return; // no es JSON utilizable: mejor callar que mandar basura
    }

    const clientes = await self.clients.matchAll({ type: 'window' });
    for (const cliente of clientes) {
      cliente.postMessage({ type: MENSAJE_API_ACTUALIZADA, url: request.url, datos });
    }
  },
};

registerRoute(
  ({ url }) => url.pathname.startsWith(`${REGION_API_PATH}/beaches`),
  new NetworkFirst({
    cacheName: 'api-playas',
    networkTimeoutSeconds: 3,
    plugins: [
      // Only complete responses are cached: a 5xx from the backend must not
      // get stuck as if it were the good data.
      new CacheableResponsePlugin({ statuses: [200] }),
      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 24 * 60 * 60 }),
      entregarRespuestaNueva,
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.
