import type { Idioma } from './IdiomaContext';
import type { ClaveTexto } from './es';
import type { EstadoBandera } from '../utils/beachHelpers';

/**
 * es→en translation of the texts coming from the backend (AEMET,
 * OpenWeather, Cruz Roja and those generated by the ranking). The backend
 * only speaks Spanish; in English we translate the known values on the
 * client and leave anything we do not recognize intact (fallback).
 *
 * Compound phrases (razonRanking, motivoBaja) are fragments
 * joined by commas — they are translated fragment by fragment.
 */

// Sky states (AEMET / OpenWeather vocabulary)
const MAPA_CIELO: Record<string, string> = {
  'despejado': 'clear',
  'soleado': 'sunny',
  // Short words generated by the backend ranking (razonRanking)
  'sol': 'sun',
  'parcialmente soleado': 'partly sunny',
  'poco nuboso': 'partly cloudy',
  'intervalos nubosos': 'cloudy intervals',
  'intervalos nubosos con lluvia escasa': 'cloudy intervals with light rain',
  'intervalos nubosos con lluvia': 'cloudy intervals with rain',
  'parcialmente nuboso': 'partly cloudy',
  'nuboso': 'cloudy',
  'nublado': 'cloudy',
  'muy nuboso': 'very cloudy',
  'cubierto': 'overcast',
  'cubierto con lluvia escasa': 'overcast with light rain',
  'cubierto con lluvia': 'overcast with rain',
  'cielo nublado': 'cloudy sky',
  'cielo despejado': 'clear sky',
  'cielo cubierto': 'overcast sky',
  'algo de nubes': 'a few clouds',
  'nubes': 'clouds',
  'nubes dispersas': 'scattered clouds',
  // OpenWeather in Spanish says "cielo claro", not "cielo despejado" (which is
  // what AEMET says). It is the detail headline on any sunny day, so
  // the leak was visible on the first line of the page. Detected by running the app.
  'cielo claro': 'clear sky',
  'lluvia': 'rain',
  'lluvia ligera': 'light rain',
  'lluvia escasa': 'light rain',
  'llovizna': 'drizzle',
  'chubascos': 'showers',
  'chubascos tormentosos': 'thundery showers',
  'tormenta': 'storm',
  'niebla': 'fog',
  'bruma': 'mist',
  'neblina': 'haze',
  'nieve': 'snow',
};

/**
 * Cardinal directions. Used standalone (as a fragment) and as the second half
 * of AEMET's compound descriptions ("flojo del noreste").
 * `nordeste`/`sudoeste` are the variants AEMET also emits.
 */
const DIRECCION_VIENTO: Record<string, string> = {
  'norte': 'north',
  'sur': 'south',
  'este': 'east',
  'oeste': 'west',
  'noreste': 'northeast',
  'nordeste': 'northeast',
  'noroeste': 'northwest',
  'sureste': 'southeast',
  'suroeste': 'southwest',
  'sudoeste': 'southwest',
};

/** Wind intensities, first half of the compound descriptions. */
const INTENSIDAD_VIENTO: Record<string, string> = {
  'en calma': 'calm',
  'calma': 'calm',
  'flojo': 'light',
  'moderado': 'moderate',
  'fresco': 'fresh',
  'fuerte': 'strong',
  'muy fuerte': 'very strong',
};

// Wind (descriptions and fragments)
const MAPA_VIENTO: Record<string, string> = {
  ...DIRECCION_VIENTO,
  ...INTENSIDAD_VIENTO,
  'viento flojo': 'light wind',
  'viento moderado': 'moderate wind',
  // `BeachScorer` emits this literal in `razonRanking`. The standalone form
  // ('fresco') is NOT added here: `MAPA_SENSACION` overrides it (see note at the merge).
  'viento fresco': 'fresh wind',
  'viento fuerte': 'strong wind',
  'sin viento': 'no wind',
  'brisa suave': 'gentle breeze',
  'brisa': 'breeze',
  'variable': 'variable',
};

// Surf / sea state
const MAPA_OLEAJE: Record<string, string> = {
  'oleaje débil': 'light surf',
  'oleaje moderado': 'moderate surf',
  'oleaje fuerte': 'heavy surf',
  'débil': 'light',
  'mar rizada': 'rippled sea',
  'rizada': 'rippled',
  'marejadilla': 'slight sea',
  'marejada': 'moderate sea',
  'fuerte marejada': 'rough sea',
  'mar gruesa': 'rough sea',
  'mar de fondo': 'groundswell',
  // Derived from wind in the backend (`wavesFromWind`, `wavesTextFromWind`).
  'agitado': 'choppy',
  'tranquilo': 'calm',
  // Rest of AEMET's Douglas scale. Careful: standalone 'moderado' and
  // 'fuerte' are NOT added, they already resolve via MAPA_VIENTO — adding them here
  // would override them due to the spread order.
  'llana': 'calm sea',
  'gruesa': 'rough sea',
  'muy gruesa': 'very rough sea',
  'arbolada': 'high sea',
  'montañosa': 'very high sea',
  'enorme': 'phenomenal sea',
};

// Thermal sensation / temperature
const MAPA_SENSACION: Record<string, string> = {
  'muy alta': 'very hot',
  'alta': 'hot',
  'agradable': 'pleasant',
  'fresca': 'cool',
  'fría': 'cold',
  'temperatura agradable': 'pleasant temperature',
  'temperatura fresca': 'cool temperature',
  'temperatura muy alta': 'very hot temperature',
  'calor': 'hot',
  'frío': 'cold',
  'fresco': 'cool',
  'muy frío': 'very cold',
  'muy caluroso': 'very hot',
  'caluroso': 'hot',
  // Full scale of `sensationFromTemp` in the backend.
  'templado': 'mild',
  'calor moderado': 'warm',
  'calor intenso': 'very hot',
};

// UV levels ("muy alto" after stripping the "índice ultravioleta" prefix)
const MAPA_UV: Record<string, string> = {
  'bajo': 'low',
  'medio': 'moderate',
  'alto': 'high',
  'muy alto': 'very high',
  'extremo': 'extreme',
  // The variants with the full prefix have been removed: `PlayaDetalle`
  // trims it before translating, so they were never actually looked up.
};

// Fragments generated by the backend ranking (razonRanking / motivoBaja)
const MAPA_RANKING: Record<string, string> = {
  'sin cobertura cruz roja': 'no Red Cross coverage',
  'bandera roja': 'red flag',
  'bandera amarilla': 'yellow flag',
  'bandera verde': 'green flag',
  'lloviendo ahora': 'raining now',
  'lluvia en la última hora': 'rain in the last hour',
  'lluvia o tormenta': 'rain or storm',
  'lluvia prevista': 'rain expected',
  'precaución': 'caution',
  'oleaje peligroso': 'dangerous surf',
  'aviso litoral': 'coastal warning',
  'aviso costero activo': 'active coastal warning',
  'sin peligro': 'no danger',
  'peligro': 'danger',
  'riesgo': 'risk',
  'riesgo importante': 'significant risk',
  'riesgo extremo': 'extreme risk',
  // Fragments from `buildCautionReason` / `buildDowngradeFactors`.
  'condiciones aceptables': 'acceptable conditions',
  'baño prohibido': 'swimming prohibited',
  'uv muy alto': 'very high UV',
  'temperatura baja': 'low temperature',
  'condiciones poco favorables': 'unfavourable conditions',
  // Exclusion reasons: they arrive as a full string, without commas.
  'baño prohibido (bandera negra)': 'swimming prohibited (black flag)',
  'bandera roja con viento muy fuerte': 'red flag with very strong wind',
  'tormenta activa': 'active storm',
  'alerta meteorológica': 'weather alert',
  'condiciones peligrosas': 'dangerous conditions',
};

// Flag colors as they arrive from Cruz Roja ("Verde"/"Amarilla"/"Roja")
const MAPA_COLORES: Record<string, string> = {
  'verde': 'green',
  'amarilla': 'yellow',
  'roja': 'red',
  // The backend also emits these two (`flagToEs`), although today the interface
  // treats them as "no data" — see known-issues/blackFlag.test.tsx.
  'negra': 'black',
  'desconocida': 'unknown',
};

// Static beach information (tipoPlaya, arena, acceso, bus...)
const MAPA_INFO: Record<string, string> = {
  'urbana': 'urban',
  'semiurbana': 'semi-urban',
  'aislada': 'secluded',
  'acantilados': 'cliffs',
  'arena dorada': 'golden sand',
  'arena dorada y grava': 'golden sand and gravel',
  'arena blanca': 'white sand',
  'arena gris': 'grey sand',
  'arena fina': 'fine sand',
  'arena oscura': 'dark sand',
  'grava': 'gravel',
  'bolos': 'pebbles',
  'roca': 'rock',
  'a pie': 'on foot',
  'en coche': 'by car',
  'en barco': 'by boat',
  'escaleras': 'stairs',
  'rampa': 'ramp',
  'urbano': 'urban',
  'interurbano': 'intercity',
  'sí': 'yes',
  'no': 'no',
  'más de 100 plazas': 'more than 100 spaces',
  'menos de 50 plazas': 'fewer than 50 spaces',
  'entre 50 y 100 plazas': '50-100 spaces',
  'no disponible': 'not available',
};

/**
 * Single lookup table. CAREFUL with the order: a repeated key is won by the
 * LAST table in the spread. Today only `'fresco'` collides, on purpose:
 * it is emitted by both wind and thermal sensation, and sensation wins
 * ('cool'). The wind side is resolved where there is context: with the
 * literal `'viento fresco'` and within the compound translation.
 *
 * The test `no hay colisiones entre tablas salvo la documentada` watches that no
 * other one sneaks in (e.g. a surf `'fuerte'` would override the wind one).
 */
const MAPA_API: Record<string, string> = {
  ...MAPA_CIELO,
  ...MAPA_VIENTO,
  ...MAPA_OLEAJE,
  ...MAPA_SENSACION,
  ...MAPA_UV,
  ...MAPA_RANKING,
  ...MAPA_COLORES,
  ...MAPA_INFO,
};

/** Tables exposed only for the test that watches for collisions. */
export const TABLAS_API = {
  MAPA_CIELO,
  MAPA_VIENTO,
  MAPA_OLEAJE,
  MAPA_SENSACION,
  MAPA_UV,
  MAPA_RANKING,
  MAPA_COLORES,
  MAPA_INFO,
};

/** Preserves the initial capitalization of the original text. */
function respetarMayuscula(original: string, traduccion: string): string {
  if (!original || !traduccion) return traduccion;
  const empiezaMayuscula = original.charAt(0) === original.charAt(0).toUpperCase();
  if (empiezaMayuscula) {
    return traduccion.charAt(0).toUpperCase() + traduccion.slice(1);
  }
  return traduccion;
}

/**
 * Connectors between intensity and direction, from most specific to least.
 * The bare space goes last so that "flojo variable" also splits.
 */
const CONECTORES_VIENTO = [' del ', ' de ', ' '];

/**
 * Translates AEMET's compound wind descriptions ("flojo del noreste"),
 * which cannot be enumerated: they are intensity × direction and the text is free-form.
 *
 * SAFETY PROPERTY: it only returns something if ALL parts are known.
 * If any fails, it returns null and the fragment is left intact. That is
 * what prevents mangling free text containing " de " or " del ", such as the
 * `acceso` field ("A pie por el recinto de la península de La Magdalena").
 *
 * Returns null if it does not recognize the form.
 */
function traducirVientoCompuesto(fragmento: string): string | null {
  const bajo = fragmento.toLowerCase();

  for (const conector of CONECTORES_VIENTO) {
    // The direction is always the last token, hence lastIndexOf.
    const corte = bajo.lastIndexOf(conector);
    if (corte < 0) continue;

    const izq = bajo.slice(0, corte).replace(/^viento /, '');
    const der = bajo.slice(corte + conector.length).replace(/^componente /, '');

    const intensidad = INTENSIDAD_VIENTO[izq];
    if (!intensidad) continue;

    if (der === 'variable') return `${intensidad} variable wind`;

    const direccion = DIRECCION_VIENTO[der];
    if (direccion) return `${intensidad} wind from the ${direccion}`;
  }

  return null;
}

function traducirFragmento(fragmento: string): string {
  if (!fragmento) return fragmento;
  const directo = MAPA_API[fragmento.toLowerCase()];
  if (directo) return respetarMayuscula(fragmento, directo);

  const viento = traducirVientoCompuesto(fragmento);
  if (viento) return respetarMayuscula(fragmento, viento);

  // Numeric fragment ("19°", "09:00 - 21:00") or free text → intact
  return fragmento;
}

/**
 * Translates an API text into the active language. In Spanish it returns the
 * original; in English it tokenizes by commas and translates each known
 * fragment, leaving the rest as is.
 */
export function traducirTextoApi(texto: string | null | undefined, idioma: Idioma): string {
  if (!texto) return '';
  if (idioma === 'es') return texto;
  return texto
    .split(',')
    .map((fragmento) => traducirFragmento(fragmento.trim()))
    .join(', ');
}

/**
 * Prepends "viento" to "flojo/fuerte" in the raw ranking reason, so it reads
 * "viento flojo" instead of "flojo". Operates on the API's Spanish, ALWAYS before
 * translating with traducirTextoApi.
 */
export function razonLegible(razonRanking: string): string {
  return razonRanking.replace(/(?<!viento )\b(flojo|fuerte)\b/i, 'viento $1');
}

/** Dictionary key for the Cruz Roja flag (replaces flagDisplayText). */
export function claveBandera(bandera?: string): ClaveTexto {
  const b = bandera?.toLowerCase() || '';
  if (b.includes('roja')) return 'bandera.roja';
  if (b.includes('amarilla')) return 'bandera.amarilla';
  if (b.includes('verde')) return 'bandera.verde';
  return 'bandera.sinDatos';
}

/**
 * Dictionary key according to the flag state: actual color, "out of
 * hours" (no flag outside surveillance) or "no data".
 */
export function claveEstadoBandera(estado: EstadoBandera, bandera?: string): ClaveTexto {
  if (estado === 'color') return claveBandera(bandera);
  if (estado === 'fueraDeHorario') return 'bandera.fueraDeHorario';
  return 'bandera.sinDatos';
}

/** Dictionary key for the wind level according to speed in m/s. */
export function claveNivelVientoMs(ms: number): ClaveTexto {
  if (ms < 3) return 'viento.sinViento';
  if (ms < 6) return 'viento.brisaSuave';
  if (ms < 10) return 'viento.moderado';
  return 'viento.fuerte';
}
